DROP TABLE if  exists books;

CREATE TABLE books(
  	id INTEGER primary key generated by default as identity,
		Url text,
		Year INTEGER,
		Author text
);

INSERT INTO books (Url, Year, Author) VALUES ('www.google.com', 1999, 'Google'), ('www.whitex2.com', 2017, 'isaac');